<?xml version="1.0" encoding="utf-8"?>
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="RT406" nillable="true" type="RT406" />
  <xs:complexType name="RT406">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="1" name="employeeRef" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="employeeName" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="departmentRef" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="departmentName" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="positionRef" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="positionName" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="branchRef" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="branchName" type="xs:string" />
      <xs:element minOccurs="1" maxOccurs="1" name="previousBalance" type="xs:decimal" />
      <xs:element minOccurs="1" maxOccurs="1" name="earned" type="xs:decimal" />
      <xs:element minOccurs="1" maxOccurs="1" name="used" type="xs:decimal" />
      <xs:element minOccurs="1" maxOccurs="1" name="adjustments" type="xs:decimal" />
      <xs:element minOccurs="1" maxOccurs="1" name="paid" type="xs:decimal" />
      <xs:element minOccurs="1" maxOccurs="1" name="balance" type="xs:decimal" />
    </xs:sequence>
  </xs:complexType>
</xs:schema>